# Generated by Django 2.1.2 on 2018-11-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
            ],
        ),
    ]
