# Generated by Django 2.1.2 on 2018-11-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20181117_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateField(),
        ),
    ]
