# Generated by Django 2.1.2 on 2018-11-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
